config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'

  root 'welcome#index'

  resources :businesses
  get '/search' => 'businesses#search', :as => 'search'
  get '/advanced_search' => 'businesses#advanced_search', :as => 'advanced_search'
  post '/advanced_search_results' => 'businesses#advanced_search_results', :as => 'advanced_search_results'
  
  get 'business/buy' => 'static_pages#buy'
  get 'business/sell' => 'static_pages#sell'
  
  get 'services/buyers' => 'static_pages#buyers'
  get 'services/sellers' => 'static_pages#sellers'
  get 'services/investors' => 'static_pages#investors'

  get 'help/value' => 'static_pages#value'
  get 'help/legal' => 'static_pages#legal'
  get 'help/financing' => 'static_pages#financing'
  

end

app/models/business.rb
class Business < ActiveRecord::Base
  include SearchCop

  search_scope :search do
    attributes :name, :industry
  end
  
  belongs_to :user
  has_many :business_images
  accepts_nested_attributes_for :business_images
  
  validates_associated :user
end

app/models/business_image.rb
class BusinessImage < ActiveRecord::Base
  belongs_to :business
  
  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :businesses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

protected
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :gender, :role, :location, :email, :password])
  end
end

app/controllers/businesses_controller.rb
class BusinessesController < ApplicationController
  def search
    @query = params[:query]
    @businesses = Business.search(@query).paginate(:page => params[:page], :per_page => 12)
  end
  
  def advanced_search
  end
  
  def advanced_search_results
    @businesses = Business.where(industry: params[:industry], city: params[:city], state: params[:state], price: (params[:price_min].to_i)..(params[:price_max].to_i))
    @businesses = @businesses.paginate(:page => params[:page], :per_page => 12)
  end
  
  def new
    @business = Business.new
  end
  
  def create
    @business = current_user.businesses.build(business_params)
    
    if @business.save
      # Sending email
      UserMailer.create_business(current_user).deliver
      
      redirect_to @business
    else
      render 'new'
    end
  end
  
  def show
    @business = Business.find_by_id(params[:id])
    
    if @business.nil?
      redirect_to root_path
    end
  end
 
private
  def business_params
    params.require(:business).permit(:name, :industry, :started, :price, :address, :tehsil, :city, :state, :num_employees)
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def buy
  end

  def sell
  end

  def buyers
  end

  def sellers
  end

  def investors
  end

  def value
  end

  def legal
  end

  def financing
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def get_all_cities
    ['Karachi',
    'Lahore',
    'Faisalabad',
    'Rawalpindi',
    'Multan',
    'Gujranwala',
    'Hyderabad',
    'Peshawar',
    'Islamabad',
    'Quetta',
    'Sargodha',
    'Sialkot',
    'Bahawalpur',
    'Sukkur',
    'Jhang',
    'Shekhupura',
    'Mardan',
    'Gujrat',
    'Larkana',
    'Kasur',
    'Rahim Yar Khan',
    'Sahiwal',
    'Okara',
    'Wah Cantonment',
    'Dera Ghazi Khan',
    'Mingora',
    'Mirpur Khas',
    'Chiniot',
    'Nawabshah',
    'Kamoke',
    'Burewala',
    'Jhelum',
    'Sadiqabad',
    'Khanewal',
    'Hafizabad',
    'Kohat',
    'Jacobabad',
    'Shikarpur',
    'Muzaffargarh',
    'Khanpur',
    'Gojra',
    'Bahawalnagar',
    'Abbottabad',
    'Muridke',
    'Pakpattan',
    'Khuzdar',
    'Jaranwala',
    'Chishtian',
    'Daska',
    'Mandi Bahauddin',
    'Ahmadpur East',
    'Kamalia',
    'Tando Adam',
    'Khairpur',
    'Dera Ismail Khan',
    'Vehari',
    'Nowshera',
    'Dadu',
    'Wazirabad',
    'Khushab',
    'Charsada',
    'Swabi',
    'Chakwal',
    'Mianwali',
    'Tando Allahyar',
    'Kot Adu',
    'Turbat']
  end
  
  def get_all_categories
    ['Accounting & Finance',
    'Hospital',
    'Advertising & Marketing',
    'Service Centers',
    'Automotive',
    'Retail stores',
    'Education',
    'Franchises',
    'Agriculture',
    'Moving & Storage',
    'Manufacturing',
    'Printing',
    'Trading',
    'Entertainment centers']
  end
end

app/helpers/businesses_helper.rb
module BusinessesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/businesses/_business.html.erb
<div class="col-md-3 top_brand_left">
	<div class="hover14 column">
		<div class="agile_top_brand_left_grid">
			<div class="agile_top_brand_left_grid1">
				<figure>
					<div class="snipcart-item block" >
						<div class="snipcart-thumb">
							<a href="<%= business_path(business.id) %>"><img title=" " alt=" " src="../assets/1.png" /></a>		
							<p><%= business.name %></p>
							<h4><%= number_to_currency(business.price, precision: 2, unit: 'Rs. ') %></h4>
						</div>
					</div>
				</figure>
			</div>
		</div>
	</div>
</div>

app/views/businesses/advanced_search.html.erb
<%= render 'layouts/header' %>

<div class="row">
  <div class="col-md-6 col-md-offset-3 col-xs-12">
    <div class="main-grid">
    	<div class="agile-grids">	
    		<div class="grids">
    			<div class="forms-grids">
    				<div class="forms3">
      				<div class="w3agile-validation w3ls-validation">
      					<div class="panel panel-widget agile-validation register-form">
      						<div class="validation-grids widget-shadow" data-example-id="basic-forms"> 
    								<div class="input-info">
    									<h3 style="color: #00bcd4!important;">Login</h3>
    								</div>
    								<div class="form-body form-body-info">
    									<%= form_tag '/advanced_search_results' do %>
    										<div class="form-group">
    										  <p class="text-white">Industry:</p>
    										  <%= select_tag :industry, options_for_select(get_all_categories.sort!, :selected => "Accounting & Finance"), {class: 'form-control', "required": "true", "style": "background-color: rgba(20, 21, 22, 0.52);"} %>
    										</div>
    										<div class="form-group">
    											<p class="text-white">City:</p>
    											<%= select_tag :city, options_for_select(get_all_cities, :selected => "Karachi"), { class: 'form-control', "required": "true", "style": "background-color: rgba(20, 21, 22, 0.52);"} %>
    										</div>
    										<div class="form-group">
    										  <p class="text-white">State:</p>
    											<%= select_tag :state, options_for_select(["Punjab", "Sindh", "KPK", "Balochistan"], :selected => "Punjab"), { class: 'form-control', "required": "true", "style": "background-color: rgba(20, 21, 22, 0.52);"} %>
    										</div>
    										<div class="form-group">
    										  <p class="text-white">Investment Range:</p>
    										  <input id="price_range" class="form-control" style="margin: 0.5em 0 1em 0;" value="Rs. 10,000.00 - Rs. 1,000,000.00"></input>
    											<%= hidden_field_tag 'price_min' %>
    											<%= hidden_field_tag 'price_max' %>
    											
    											<div id="the_slider"></div>
    										</div>
    										
    										<!-- submit button-->
    										<div class="bottom">
    											<div class="form-group">
    												<%= submit_tag "Search Business", class: "btn btn-primary" %>
    											</div>
    											<div class="clearfix"> </div>
    										</div>
    										<!-- //submit button-->
    									<% end %>
    								</div>
      						</div>
      					</div>
      				</div>
    				</div> <!--end of forms3-->
    				<div class="clear"> </div>
    			</div>
    		</div>
    	</div>
    </div> <!--end of maingrid-->
  </div>
</div>

<script>
  $(document).ready(function() {
    var slider = $("#the_slider").slider({
        range: true,
        min: 10000,
        max: 10000000,
        values: [10000, 1000000],
        slide: function(event, ui) {
          $("#price_min").val(ui.values[0]);
          $("#price_max").val(ui.values[1]);
          $("#price_range").val('Rs. '+ui.values[0].toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, '$1,')+ " - Rs. " + ui.values[1].toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, '$1,'));
        }
    });
    $("#price_min").val(slider.slider("values")[0]);
    $("#price_max").val(slider.slider("values")[1]);
    $("#price_range").val('Rs. '+ui.values[0].toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, '$1,')+ " - Rs. " + ui.values[1].toFixed(2).replace(/(\d)(?=(\d{3})+\.)/g, '$1,'));
  });
</script>

<%= render 'layouts/footer' %>

app/views/businesses/advanced_search_results.html.erb
<%= render 'layouts/header' %>

<div class="top-brands">
	<div class="container">
		<h3><%= @businesses.count %> RESULT(S) FOUND</h3>
  		<div class="agile_top_brands_grids">
  		  <% @businesses.each_with_index do |business, index| %>
  		    <%= render 'business', business: business %>
  		    <% if index % 4 == 3 %>
  		      <p style="visibility: hidden;">Hello</p>
  		    <% end %>
  		  <% end %>
  		</div>
  	</div>
  	
  	<center>
  	 <%= will_paginate @businesses, :previous_label => '← Prev' %>
  	</center>
  </div>
</div>

<%= render 'layouts/footer' %>

app/views/businesses/new.html.erb
<%= render 'layouts/header' %>

<div class="row">
  <div class="col-md-6 col-md-offset-3 col-xs-12">
    <div class="main-grid">
    	<div class="agile-grids">	
    		<div class="grids">
    			<div class="forms-grids">
    				<div class="forms3">
      				<div class="w3agile-validation w3ls-validation">
      					<div class="panel panel-widget agile-validation register-form">
      						<div class="validation-grids widget-shadow" data-example-id="basic-forms"> 
    								<div class="input-info">
    									<h3 style="color: #00bcd4!important;">Login</h3>
    								</div>
    								<div class="form-body form-body-info">
    									<%= form_for :business, url: businesses_path, :html => {:id => "new_business_form"} do |f| %>
    									  <!-- form errors-->
    									  <% if @business.errors.any? %>
                          <div id="error_explanation">
                            <h2>
                              <%= pluralize(@business.errors.count, "error") %> found
                            </h2>
                            <ul>
                              <% @business.errors.full_messages.each do |msg| %>
                                <li><%= msg %></li>
                              <% end %>
                            </ul>
                          </div>
                        <% end %>
                        <!-- //form errors-->
    									
    										<div class="form-group">
    											<%= f.text_field :name, autofocus: true, class: 'form-control', "required": "true", placeholder: 'Enter your Business Name' %>
    										</div>
    										<div class="form-group">
      		                  <%= f.select :industry, options_for_select(get_all_categories.sort!, :selected => "Accounting & Finance"), {}, { class: 'form-control', "required": "true", "style": "background-color: rgba(20, 21, 22, 0.52);"} %>
    										</div>
    										<div class="form-group">
    										  <p style="margin-bottom: 1em; color: white">Started on:</p>
    										  <%= f.date_field :started, class: 'form-control', "required": "true" %>
    										</div>
    										<div class="form-group">
    											<%= f.number_field :price, class: 'form-control', "required": "true", placeholder: 'Estimated price of Business' %>
    										</div>
    										<div class="form-group">
    											<%= f.text_field :address, class: 'form-control', "required": "true", placeholder: 'Enter your Business\'s Address' %>
    										</div>
    										<div class="form-group">
    											<%= f.text_field :tehsil, class: 'form-control', "required": "true", placeholder: 'Enter your Business\'s Tehsil' %>
    										</div>
    										<div class="form-group">
    											<%= f.select :state, options_for_select(get_all_cities, :selected => "Karachi"), {}, { class: 'form-control', "required": "true", "style": "background-color: rgba(20, 21, 22, 0.52);"} %>
    										</div>
    										<div class="form-group">
    											<%= f.select :state, options_for_select(["Punjab", "Sindh", "KPK", "Balochistan"], :selected => "Punjab"), {}, { class: 'form-control', "required": "true", "style": "background-color: rgba(20, 21, 22, 0.52);"} %>
    										</div>
    										<div class="form-group">
    											<%= f.number_field :num_employees, class: 'form-control', "required": "true", placeholder: 'Enter number of Employees' %>
    										</div>
    										
    										<!-- submit button-->
    										<div class="bottom">
    											<div class="form-group">
    												<%= f.submit "Save Business", class: "btn btn-primary" %>
    											</div>
    											<div class="clearfix"> </div>
    										</div>
    										<!-- //submit button-->
    									<% end %>
    								</div>
      						</div>
      					</div>
      				</div>
    				</div> <!--end of forms3-->
    				<div class="clear"> </div>
    			</div>
    		</div>
    	</div>
    </div> <!--end of maingrid-->
  </div>
</div>

<%= render 'layouts/footer' %>

<%= javascript_include_tag "valida.2.1.6.min", "data-turbolinks-track" => true  %>
<%= javascript_include_tag "validator.min", "data-turbolinks-track" => true  %>

<script>
$(document).ready(function(){
    $('#new_business_form').valida();
    
    $(".dropdown").hover(            
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideDown("fast");
            $(this).toggleClass('open');        
        },
        function() {
            $('.dropdown-menu', this).stop( true, true ).slideUp("fast");
            $(this).toggleClass('open');       
        }
    );
});
</script>

app/views/businesses/search.html.erb
<%= render 'layouts/header' %>

<div class="top-brands">
	<div class="container">
		<h3><%= @businesses.count %> RESULT(S) FOUND</h3>
  		<div class="agile_top_brands_grids">
  		  <% @businesses.each_with_index do |business, index| %>
  		    <%= render 'business', business: business %>
  		    <% if index % 4 == 3 %>
  		      <p style="visibility: hidden;">Hello</p>
  		    <% end %>
  		  <% end %>
  		</div>
  	</div>
  	
  	<center>
  	 <%= will_paginate @businesses, :previous_label => '← Prev' %>
  	</center>
  </div>
</div>

<%= render 'layouts/footer' %>

app/views/businesses/show.html.erb
<%= render 'layouts/header' %>

<div class="agileinfo_single">
	<center><h5><%= @business.name %></h5></center>
	<div class="col-md-4 agileinfo_single_left">
		<img id="example" src="/assets/76.png" alt=" " class="img-responsive" />
	</div>
	<div class="col-md-8 agileinfo_single_right">
		<div class="w3agile_description">
			<h4>Description :</h4>
			<p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui 
				officia deserunt mollit anim id est laborum.Duis aute irure dolor in 
				reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla 
				pariatur.</p>
			
			<strong><p style="margin: 1em 0 1em 0;"><%= @business.started.strftime("Started on %m %B, %Y") %></p></strong>
			
			<h4>Location :</h4>
			<p><%= @business.address %>, <%= @business.tehsil %>, <%= @business.city %>, <%= @business.state %></p>
		</div>
		<div class="snipcart-item block">
			<div class="snipcart-thumb agileinfo_single_right_snipcart">
				<h4>Rs. <%= @business.price %></h4>
			</div>
			<div class="snipcart-details agileinfo_single_right_details">
				<form action="#" method="post">
					<fieldset>
						<input type="hidden" name="business_id" value="<%= @business.id %>" />
						
						<input type="submit" name="submit" value="Ask for Seller Info." class="button" />
					</fieldset>
				</form>
			</div>
		</div>
	</div>
	<div class="clearfix"> </div>
</div>

<%= render 'layouts/footer' %>

app/views/layouts/_header.html.erb
<div class="agileits_header">
	<div class="w3l_offers">
		<p>Today's special Offers !</p>
	</div>
	<div class="w3l_search">
		<form action="/search" method="get">
			<input type="text" name="query" value="Search a product..." onfocus="this.value = '';" onblur="if (this.value == '') {this.value = 'Search a product...';}" required="">
			<input type="submit" value=" ">
		</form>
	</div>
	<div class="w3l_header_right">
		<ul>
			<li class="dropdown profile_details_drop">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user" aria-hidden="true"></i><span class="caret"></span></a>
				<div class="mega-dropdown-menu">
					<div class="w3ls_vegetables">
						<ul class="dropdown-menu drp-mnu">
						  <% if user_signed_in? %>
						    <li>
								  <%= link_to destroy_user_session_path, method: :delete do %>
                    Sign Out
                  <% end %>
								</li>
						  <% else %>
						    <li>
								  <%= link_to 'Sign In', new_user_session_path %>
								</li> 
								<li>
								  <%= link_to 'Sign Up', new_user_registration_path %>
								</li>
						  <% end %>
						</ul>
					</div>                  
				</div>	
			</li>
		</ul>
	</div>
	<div class="w3l_header_right1">
		<h2>
		  <% if user_signed_in? %>
		    <%= link_to 'Sell Here', new_business_path %>
		  <% else %>
		    <%= link_to 'Sell Here', new_user_session_path %>
		  <% end %>
		</h2>
	</div>
	<div class="clearfix"> </div>
</div>

<div class="logo_products">
	<div class="container">
		<div class="w3ls_logo_products_left">
			<h1><a href="<%= root_path %>"><span>OLX for</span> Business</a></h1>
		</div>
		<div class="w3ls_logo_products_left1">
			<ul class="special_items">
			  <li><a href="/advanced_search">Advanced Search</a><span class="divider">/</span></li>
			  <li class="dropdown special_item">
          <div>
            How to
            <span class="caret"></span>
          </div>
          <ul class="dropdown-menu">
            <li><a href="/business/buy">Buy Business</a></li>
            <li><a href="/business/sell">Sell Business</a></li>
          </ul>
        </li>
        <span class="divider">/</span>
        
        <li><a href="/#stories">Success Stories</a><span class="divider">/</span></li>
        
        <li class="dropdown special_item">
          <div>
            Our Services
            <span class="caret"></span>
          </div>
          <ul class="dropdown-menu">
            <li><a href="/services/buyers">For Buyers</a></li>
            <li><a href="/services/sellers">For Sellers</a></li>
            <li><a href="/services/investors">For Investors</a></li>
          </ul>
        </li>
        <span class="divider">/</span>
        
        <li class="dropdown special_item">
          <div>
            Business Help
            <span class="caret"></span>
          </div>
          <ul class="dropdown-menu">
            <li><a href="/help/value">Find Value of Your Business</a></li>
            <li><a href="/help/legal">Legal Help from Lawyers</a></li>
            <li><a href="/help/financing">Financing for your Business</a></li>
          </ul>
        </li>
        <span class="divider">/</span>
			  
			  <li><a href="/#footer">Contact Us</a></li>
				<!--<li><a href="events.html">Events</a><i>/</i></li>-->
			</ul>
		</div>
		<div class="clearfix"> </div>
	</div>
</div>

<hr class="header-hr"></hr>
<!-- //header -->

app/views/welcome/index.html.erb
<%= render 'layouts/header' %>
  
<!-- banner -->
<div class="banner">
	<div class="w3l_banner_nav_left">
		<nav class="navbar nav_bottom">
		 <!-- Brand and toggle get grouped for better mobile display -->
		  <div class="navbar-header nav_2">
			  <button type="button" class="navbar-toggle collapsed navbar-toggle1" data-toggle="collapse" data-target="#bs-megadropdown-tabs">
				<span class="sr-only">Toggle navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			  </button>
		   </div> 
		   
		  <!-- search business section-->
			<div class="collapse navbar-collapse" id="bs-megadropdown-tabs">
			  <h3>Search Business by </h3>
				<ul class="nav navbar-nav nav_1">
				  <% get_all_categories.sort.each do |business| %>
				    <li><%= link_to business, search_path(:query => business) %></li>
				  <% end %>
				</ul>
			</div>
			<!-- //search business section-->
		</nav>
	</div>
	<div class="w3l_banner_nav_right">
		<section class="slider">
			<div class="flexslider">
				<ul class="slides">
					<li>
						<div class="w3l_banner_nav_right_banner">
							<h3>Make your <span>food</span> with Spicy.</h3>
							<div class="more">
								<a href="products.html" class="button--saqui button--round-l button--text-thick" data-text="Shop now">Shop now</a>
							</div>
						</div>
					</li>
					<li>
						<div class="w3l_banner_nav_right_banner1">
							<h3>Make your <span>food</span> with Spicy.</h3>
							<div class="more">
								<a href="products.html" class="button--saqui button--round-l button--text-thick" data-text="Shop now">Shop now</a>
							</div>
						</div>
					</li>
					<li>
						<div class="w3l_banner_nav_right_banner2">
							<h3>upto <i>50%</i> off.</h3>
							<div class="more">
								<a href="products.html" class="button--saqui button--round-l button--text-thick" data-text="Shop now">Shop now</a>
							</div>
						</div>
					</li>
				</ul>
			</div>
		</section>
		
		<!-- flexSlider -->
			<link rel="stylesheet" href="css/flexslider.css" type="text/css" media="screen" property="" />
			<script defer src="js/jquery.flexslider.js"></script>
			<script type="text/javascript">
			$(window).load(function(){
			  $('.flexslider').flexslider({
				animation: "slide",
				start: function(slider){
				  $('body').removeClass('loading');
				}
			  });
			});
		  </script>
		<!-- //flexSlider -->
	</div>
	<div class="clearfix"></div>
</div>

<div class="banner_bottom">
	<div class="wthree_banner_bottom_left_grid_sub">
		</div>
		<div class="wthree_banner_bottom_left_grid_sub1">
			<div class="col-md-4 wthree_banner_bottom_left">
				<div class="wthree_banner_bottom_left_grid">
					<img src="assets/4.jpg" alt=" " class="img-responsive" />
					<div class="wthree_banner_bottom_left_grid_pos">
						<h4>Discount Offer <span>25%</span></h4>
					</div>
				</div>
			</div>
			<div class="col-md-4 wthree_banner_bottom_left">
				<div class="wthree_banner_bottom_left_grid">
					<img src="assets/5.jpg" alt=" " class="img-responsive" />
					<div class="wthree_banner_btm_pos">
						<h3>introducing <span>best store</span> for <i>groceries</i></h3>
					</div>
				</div>
			</div>
			<div class="col-md-4 wthree_banner_bottom_left">
				<div class="wthree_banner_bottom_left_grid">
					<img src="assets/6.jpg" alt=" " class="img-responsive" />
					<div class="wthree_banner_btm_pos1">
						<h3>Save <span>Upto</span> $10</h3>
					</div>
				</div>
			</div>
			<div class="clearfix"> </div>
		</div>
		<div class="clearfix"> </div>
</div>
<!-- //banner -->
	
<!-- random businesses -->
<div class="top-brands">
	<div class="container">
		<h3>Hot Offers</h3>
		<div class="agile_top_brands_grids">
		  <% Business.order("RANDOM()").limit(4).each_with_index do |business, index| %>
		    <%= render 'businesses/business', business: business %>
		  <% end %>
					
			<div class="clearfix"> </div>
		</div>
	</div>
</div>
<!-- //random businesses -->

<!-- success stories -->
<div id="stories" class="testimonials">
	<div class="container">
		<h3>Success Stories</h3>
			<div class="w3_testimonials_grids">
				<div class="wmuSlider example1 animated wow slideInUp" data-wow-delay=".5s">
					<div class="wmuSliderWrapper">
						<article style="position: absolute; width: 100%; opacity: 0;"> 
							<div class="banner-wrap">
								<div class="col-md-6 w3_testimonials_grid">
									<p><i class="fa fa-quote-right" aria-hidden="true"></i>Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis 
										voluptatibus maiores alias consequatur aut perferendis doloribus asperiores 
										repellat.</p>
									<h4>Andrew Smith <span>Customer</span></h4>
								</div>
								<div class="col-md-6 w3_testimonials_grid">
									<p><i class="fa fa-quote-right" aria-hidden="true"></i>Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis 
										voluptatibus maiores alias consequatur aut perferendis doloribus asperiores 
										repellat.</p>
									<h4>Thomson Richard <span>Customer</span></h4>
								</div>
								<div class="clearfix"> </div>
							</div>
						</article>
						<article style="position: absolute; width: 100%; opacity: 0;"> 
							<div class="banner-wrap">
								<div class="col-md-6 w3_testimonials_grid">
									<p><i class="fa fa-quote-right" aria-hidden="true"></i>Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis 
										voluptatibus maiores alias consequatur aut perferendis doloribus asperiores 
										repellat.</p>
									<h4>Crisp Kale <span>Customer</span></h4>
								</div>
								<div class="col-md-6 w3_testimonials_grid">
									<p><i class="fa fa-quote-right" aria-hidden="true"></i>Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis 
										voluptatibus maiores alias consequatur aut perferendis doloribus asperiores 
										repellat.</p>
									<h4>John Paul <span>Customer</span></h4>
								</div>
								<div class="clearfix"> </div>
							</div>
						</article>
						<article style="position: absolute; width: 100%; opacity: 0;"> 
							<div class="banner-wrap">
								<div class="col-md-6 w3_testimonials_grid">
									<p><i class="fa fa-quote-right" aria-hidden="true"></i>Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis 
										voluptatibus maiores alias consequatur aut perferendis doloribus asperiores 
										repellat.</p>
									<h4>Rosy Carl <span>Customer</span></h4>
								</div>
								<div class="col-md-6 w3_testimonials_grid">
									<p><i class="fa fa-quote-right" aria-hidden="true"></i>Itaque earum rerum hic tenetur a sapiente delectus, ut aut reiciendis 
										voluptatibus maiores alias consequatur aut perferendis doloribus asperiores 
										repellat.</p>
									<h4>Rockson Doe <span>Customer</span></h4>
								</div>
								<div class="clearfix"> </div>
							</div>
						</article>
					</div>
				</div>
				<script src="js/jquery.wmuSlider.js"></script> 
				<script>
					$('.example1').wmuSlider();         
				</script> 
			</div>
	</div>
</div>
<!-- //success stories -->

<%= render 'layouts/footer' %>